// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic type structure
export type Database = {
  public: {
    Tables: {
      // Tables will be synced from Supabase
      [key: string]: any
    }
  }
}

